<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Create_Account</title>
</head>
<body>
<%
out.println("<!DOCTYPE html>");
out.println("<html>");
out.println("");
out.println("<head>");
out.println("    <meta charset=\"utf-8\">");
out.println("    <title>Register Form</title>");
out.println("    <link rel=\"stylesheet\" href=\"style.css\">");
out.println("");
out.println("    <script src=\"jquery.js\"></script>");
out.println("    <script>");
out.println("        function checkPasswordMatch() {");
out.println("            var password = $(\"#txtNewPassword\").val();");
out.println("            var confirmPassword = $(\"#txtConfirmPassword\").val();");
out.println("            if (password != confirmPassword)");
out.println("                $(\"#CheckPasswordMatch\").html(\"Passwords does not match!\");");
out.println("            else");
out.println("                $(\"#CheckPasswordMatch\").html(\"Passwords match.\");");
out.println("");
out.println("        }");
out.println("        $(document).ready(function () {");
out.println("            $('.error').hide();");
out.println("");
out.println("            $(\".form-footer\").find(\".btn\").click(function () {");
out.println("                var email = $('#email').val();");
out.println("                if (email == '') {");
out.println("                    $('#email').next().show();");
out.println("                    return false;");
out.println("                }");
out.println("                if (IsEmail(email) == false) {");
out.println("                    $('#invalid_email').show();");
out.println("                    return false;");
out.println("                }");
out.println("");
out.println("            });");
out.println("            $(\"#txtConfirmPassword\").keyup(checkPasswordMatch);");
out.println("        });");
out.println("");
out.println("        function IsEmail(email) {");
out.println("            var regex = /^([a-zA-Z0-9_\\.\\-\\+])+\\@(([a-zA-Z0-9\\-])+\\.)+([a-zA-Z0-9]{2,4})+$/;");
out.println("            if (!regex.test(email)) {");
out.println("                return false;");
out.println("            } else {");
out.println("                return true;");
out.println("            }");
out.println("        }");
out.println("        ");
out.println("");
out.println("    </script>");
out.println("");
out.println("</head>");
out.println("");
out.println("<body>");
out.println("    <form class=\"signup-form\" action=\"\" method=\"post\" id=\"contactform\">");
out.println("");
out.println("");
out.println("        <div class=\"form-header\">");
out.println("            <h1>Create Account</h1>");
out.println("        </div>");
out.println("");
out.println("");
out.println("        <div class=\"form-body\">");
out.println("");
out.println("");
out.println("            <div class=\"horizontal-group\">");
out.println("                <div class=\"form-group left\">");
out.println("                    <label for=\"firstname\" class=\"label-title\">First name *</label>");
out.println("                    <input type=\"text\" id=\"firstname\" class=\"form-input\" placeholder=\"Enter your first name\"");
out.println("                        required=\"required\" />");
out.println("                </div>");
out.println("                <div class=\"form-group right\">");
out.println("                    <label for=\"lastname\" class=\"label-title\">Last name</label>");
out.println("                    <input type=\"text\" id=\"lastname\" class=\"form-input\" placeholder=\"Enter your last name\" />");
out.println("                </div>");
out.println("            </div>");
out.println("");
out.println("");
out.println("            <div class=\"form-group\">");
out.println("                <label for=\"email\" class=\"label-title\">Email*</label>");
out.println("                <input type=\"email\" id=\"email\" class=\"form-input\" placeholder=\"Enter your email\" required=\"required\">");
out.println("                <span class=\"error\" id=\"invalid_email\">Email-id is invalid</span>");
out.println("            </div>");
out.println("");
out.println("");
out.println("            <div class=\"horizontal-group\">");
out.println("                <div class=\"form-group left\">");
out.println("                    <label for=\"password\" class=\"label-title\">Password *</label>");
out.println("                    <input type=\"password\" id=\"txtNewPassword\" class=\"form-input\" placeholder=\"Enter your password\"");
out.println("                        required=\"required\">");
out.println("                </div>");
out.println("");
out.println("                <div class=\"form-group right\">");
out.println("                    <label for=\"confirm-password\" class=\"label-title\">Confirm Password *</label>");
out.println("                    <input type=\"password\" class=\"form-input\" id=\"txtConfirmPassword\"");
out.println("                        placeholder=\"Enter your password again\" required=\"required\">");
out.println("                    <div class=\"registrationFormAlert\" style=\"color:green;\" id=\"CheckPasswordMatch\">");
out.println("                    </div>");
out.println("");
out.println("");
out.println("                </div>");
out.println("");
out.println("");
out.println("                <div class=\"horizontal-group\">");
out.println("                    <div class=\"form-group left\">");
out.println("                        <label class=\"label-title\">Gender *</label>");
out.println("                        <div class=\"input-group\">");
out.println("                            <label for=\"male\"><input type=\"radio\" name=\"gender\" value=\"male\" id=\"male\"> Male</label>");
out.println("                            <label for=\"female\"><input type=\"radio\" name=\"gender\" value=\"female\" id=\"female\">");
out.println("                                Female</label>");
out.println("                            <label for=\"others\"><input type=\"radio\" name=\"gender\" value=\"others\" id=\"others\">");
out.println("                                Others</label>");
out.println("                        </div>");
out.println("                    </div>");
out.println("                    <div class=\"form-group right\">");
out.println("                        <label class=\"label-title\">Hobbies</label>");
out.println("                        <div>");
out.println("                            <label><input type=\"checkbox\" value=\"Web\">Music</label>");
out.println("                            <label><input type=\"checkbox\" value=\"iOS\">Sports</label>");
out.println("                            <label><input type=\"checkbox\" value=\"Andriod\">Travel</label>");
out.println("                            <label><input type=\"checkbox\" value=\"Game\">Movies</label>");
out.println("                        </div>");
out.println("                    </div>");
out.println("                </div>");
out.println("");
out.println("");
out.println("                <div class=\"horizontal-group\">");
out.println("                    <div class=\"form-group left\">");
out.println("                        <label class=\"label-title\">Source of Income *</label>");
out.println("                        <select class=\"form-input\" id=\"level\">");
out.println("                            <option value=\"B\">Employed</option>");
out.println("                            <option value=\"I\">Self-employed</option>");
out.println("                            <option value=\"A\">Unemployed</option>");
out.println("                        </select>");
out.println("                    </div>");
out.println("                    <div class=\"form-group right\">");
out.println("                        <label for=\"experience\" class=\"label-title\">Income</label>");
out.println("                        <input type=\"range\" min=\"10\" max=\"100\" step=\"10\" value=\"0\" id=\"experience\" class=\"form-input\"");
out.println("                            onChange=\"change();\" style=\"height:28px;width:78%;padding:0;\">");
out.println("                        <span id=\"range-label\">20K</span>");
out.println("                    </div>");
out.println("                </div>");
out.println("");
out.println("");
out.println("                <div class=\"horizontal-group\">");
out.println("                    <div class=\"form-group left\">");
out.println("                        <label for=\"choose-file\" class=\"label-title\">Upload Profile Picture *</label>");
out.println("                        <input type=\"file\" id=\"choose-file\" size=\"80\">");
out.println("                    </div>");
out.println("                    <div class=\"form-group right\">");
out.println("                        <label for=\"experience\" class=\"label-title\">Age *</label>");
out.println("                        <input type=\"number\" min=\"18\" max=\"150\" value=\"18\" class=\"form-input\" required=\"required\">");
out.println("");
out.println("                    </div>");
out.println("                </div>");
out.println("            </div>");
out.println("");
out.println("");
out.println("            <div class=\"form-group\">");
out.println("                <label for=\"choose-file\" class=\"label-title\">Bio *</label>");
out.println("                <textarea class=\"form-input\" rows=\"3\" cols=\"50\" style=\"height:auto\"  required=\"required\"></textarea>");
out.println("            </div>");
out.println("        </div>");
out.println("        ");
out.println("");
out.println("        <div class=\"form-footer\">");
out.println("            <span>required *</span>");
out.println("            <button type=\"submit\" class=\"btn\" value=\"Validate\">Create</button>");
out.println("        </div>");
out.println("");
out.println("    </form>");
out.println("");
out.println("");
out.println("");
out.println("");
out.println("</body>");
out.println("");
out.println("</html>");
%>
</body>
</html>